import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/shared/navbar/navbar";
import Provider from "./provider";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, useMessages } from "next-intl";
import "./globals.css";

interface Props {
  children: React.ReactNode;
  params: { locale: string };
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = ["uz", "ru"];

export default function RootLayout({ children, params: { locale } }: Props) {
  if (!locales.includes(locale as any)) notFound();

  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Provider>
            <Navbar />
            <main>{children}</main>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
